/*
=========================================================
Analysis 3: Customer Lifetime Value (CLV)
=========================================================

Business Requirement:
Calculate the total revenue generated by each customer
to identify high-value customers.

=========================================================
*/

SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.total_amount) AS Customer_Lifetime_Value
FROM Customers c
INNER JOIN Orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY
    Customer_Lifetime_Value DESC;

/*
Business Insight:
Customers with the highest lifetime value contribute the
most revenue and should be prioritized for retention,
loyalty programs, and personalized marketing.
*/
